/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package arbolesb.Gui;

import arbolesb.Main;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author luisponcedeleon
 */
public class DOrden extends javax.swing.JDialog {

    /**
     * Creates new form dOrden
     */
    public DOrden(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bOrden = new javax.swing.JButton();
        tOrden = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Orden del arbol");
        setAlwaysOnTop(true);
        setResizable(false);

        bOrden.setText("Ingresar Orden");
        bOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdenActionPerformed(evt);
            }
        });

        tOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tOrdenActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese el orden del arbol");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(54, 54, 54)
                        .add(tOrden, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(39, 39, 39)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(bOrden, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel1))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(tOrden, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(bOrden)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdenActionPerformed
        try {
            Main.EstablecerOrden(Integer.parseInt(tOrden.getText()));
            
            this.dispose();
            
            Main.ActualizarInfo();
        } catch (Exception ex) {
            Logger.getLogger(DOrden.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error en Ingreso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bOrdenActionPerformed

    private void tOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tOrdenActionPerformed
        try {
            Main.EstablecerOrden(Integer.parseInt(tOrden.getText()));
            
            this.dispose();
            
            Main.ActualizarInfo();
        } catch (Exception ex) {
            Logger.getLogger(DOrden.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error en Ingreso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tOrdenActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tOrden;
    // End of variables declaration//GEN-END:variables
}
